matrix:
  include:
  - language: python
    python: 2.7
    services:
    - docker
    install:
    - docker images
    script:
    - docker build -t app .
  - language: ruby
    script: bundle exec rake spec
    bundler_args: "--without=debug"
    services:
    - redis-server
    addons:
      postgresql: '9.4'
      code_climate:
        repo_token:
          secure: aeLLEEn+42UCOH2nEuuebv8WnnTRAM4js7+61720OM4jnSgTZjluGWGecufjPagIbj2tZ2ldXMEs+SQbfy6PJC9QKcHuo6/OUehg1BcTALqPCvfzKHw55nvFZbFUvW+2Oewnd0Gufmy0GmhLldk8+ElSlk2jTxnBgKuXil/xpZU=
    before_install:
      - gem install bundler
    before_script:
    - cp config/database.travis.yml config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    after_script:
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    env:
    - aws_secret_key=testing
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=e497915c5dac45d97b9e51fdf3620b7932e69f59230e3034cab50bd937430590
    deploy:
    - provider: script
      skip_cleanup: true
      script: "./.travis-deploy.sh"
      on:
        branch: master
