version: '3.3'
  # Based on:
  # https://github.com/massenz/docker-cassandra/blob/develop/docker-compose.yml

services:
#TODO: Work in progress
# There is no official docker image for Kairos 2017-12-18
#  kairos:
#    image: kairos
#    ports:
#      - "8080:8080"
#      - "4242:4242"

# Check if cassandra cluster is working:
# docker-compose exec cassandra-1 nodetool status
  cassandra-1:
    image: cassandra
    ports:
      # no need to expose all ports?
      - "7000:7000" # Internode, cluster communication
      - "7001:7001" # TLS Internode
      - "7199:7199" # JMX
      - "9042:9042" # CQL native transport
      - "9160:9160" # Thrift client API
    #volumes:
      #- sck-cassandra:/var/lib/cassandra

  cassandra-2:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-1 # Use IP if on different servers
    depends_on:
      - cassandra-1
    #volumes:
      #- sck-cassandra:/var/lib/cassandra
      #
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'


  cassandra-3:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-1 # Use IP if on different servers
    depends_on:
      - cassandra-1
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'


volumes:
  sck-cassandra:
