version: '3.3'

services:
  db:
    image: postgres:10
    volumes:
      - sck-postgres:/var/lib/postgresql/data

  redis:
    image: redis:4

  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mqtt
    volumes:
      - "./:/app"
    command: rails server -p 3000 -b '0.0.0.0'
    environment:
      # For this to take effect, remove init/timeout, and in Gemfile, fix "rack-timeout" to not require anything.
      RACK_TIMEOUT_SERVICE_TIMEOUT: 25
      #RACK_TIMEOUT_WAIT_TIMEOUT: 30
      #RACK_TIMEOUT_WAIT_OVERTIME: 60
      #RACK_TIMEOUT_SERVICE_PAST_WAIT: false

  sidekiq:
    build: .
    env_file: .env
    depends_on:
      - app
      - redis
    command: bundle exec sidekiq

  mqtt-task:
    build: .
    env_file: .env
    depends_on:
      - app
    command: bundle exec rake mqtt:sub

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
#    volumes:
#      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"

  web:
    env_file: .env
    image: steveltn/https-portal
    depends_on:
      - app
    environment:
      DOMAINS: "${MY_DOMAIN}"
      STAGE: "${MY_STAGE}" #local or production, this decides if you want a real certificate from LE, or not
    # expose the port we configured Nginx to bind to (it is ok to expose externally)
    ports:
      - 80:80
      - 443:443

  push:
    image: smartcitizen/push
    environment:
      - REDIS_URL=redis://redis:6379/4

volumes:
  sck-postgres:
