name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test with Rake
      run: |
        uname -a
        cat /etc/os-release
        apt-get install libpq-dev
        ls $RUNNER_TOOL_CACHE/Ruby
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
